### ISSUE TITLE
[BUG](?) Cannot enable plugin, example broken

### ISSUE THREAD

**Issue by zortordor** [MASSHUU12/godot-interaction-system#21]
**Describe the bug**
When I try to activate the plugin, it says that there is an error in “InteractionSystem.cs”.
When running the example scene, the following error appears: 

“E 0:00:00:0797   can_instantiate: Cannot instance script because the associated class could not be found. Script: 'res://examples/player/3D/Player.cs'. Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly (it's case-sensitive).
  <C++ Error>    Method/function failed. Returning: false
  <C++ Source>   modules/mono/csharp_script.cpp:2423 @ can_instantiate()”

**Other information**
— Godot version: 4.2.mono
— .NET: 8
— Add-on version: 2.0.0

**Additional context**

**Comment by MASSHUU12** [comment]
Hey, thank you for your report.

The plugin version `2.0.0` was created under Godot `4.1.1.mono` (I should point that out in the README, but it's too late for that). It is a very old version with several bugs (e.g., the path to examples is wrong) and I advise against using it.

I checked the error you reported using the Godot `4.2.1.stable.mono` version and .NET 6, 7 and 8. At first there was indeed a problem, but only with the path to the examples, directly running the scenes works. Although Godot screams that “Unable to load addon…” the plugin also works without an issue.

I would suggest [downloading](https://github.com/MASSHUU12/godot-interaction-system/releases/tag/v2.0.0) the plugin again, possibly deleting the generated `.godot` folder and trying to run everything again, and ideally you should use the `latest` version of the plugin, as this one is `unsupported`.

The [latest](https://github.com/MASSHUU12/godot-interaction-system/releases/tag/v2.3.0) version of the plugin (2.3.0) works under Godot `4.1`, `4.2` and `4.3` (tested versions are 4.1.4.rc1.mono, 4.2.1.stable.mono and 4.3.dev2.mono).

Of course, a lot has changed between versions, but in my opinion for the better and using the plugin should be easier.

If you have additional questions, you can reopen this issue or create a new one.

**Comment by zortordor** [comment]
Tried all the suggestions, still no progress. Also, idk if it's related, but the .cs scripts don't have any highlighting. I guess my setup is messed up somehow.

**Comment by MASSHUU12** [comment]
I'd really like to help you, but as far as I know, this is the first such situation for my plugin to completely fail to work. No one else has reported similar problems to me, and I've tested it myself on various configurations.

Have you checked the latest version of my plugin? Do other plugins/your code written in C# work in Godot?

If you are using a system other than Windows, you may be missing something, such as [Mono](https://www.mono-project.com/download/stable/#download-lin) for Linux.

Maybe you can find some useful hints in the [documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_basics.html).

**Comment by zortordor** [comment]
Got it working, sorry for the ruckus. Pressing "Create C# solution" in the Project tab did it.
